# Generated by Django 5.2.3 on 2025-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user/default.png', upload_to='profile_pics/'),
        ),
    ]
