# Generated by Django 5.2.3 on 2025-06-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
